name: Issue Greet
# https://github.com/marketplace/actions/first-interaction

on: [issues] 

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Note : Issue is still open to others. Only a merged PR is evaluated as a contribution, till then it is open to all.'
